services:
  fast_api_backend:
    build:
      context: .
    depends_on:
      postgres_database:
        condition: service_healthy
    ports:
      - "8000:8000"
  postgres_database:
    image: postgres:17
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres_database}
      - POSTGRES_DB=${POSTGRES_DB:-autoapply}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
